clc;clear;
addpath(genpath('C:\Users\Usman\OneDrive\Hedge\Google 5min'));
list = {'SPY.csv'}
interval = 300; % 60 for 1 min data, 300 for 5 min data

filename = 'Spy5Min.xlsx';

%loop though each file
FullDates = 0;

for x=1:size(list,2);
    
    [num,txt,raw] = xlsread(list{1,x});
    raw = raw(8:end,:);
    try
    TimeStamp = num(:,1);
    catch
        continue;
    end
    Open =  num(:,5);
    High =  num(:,3);
    Low =  num(:,4);
    Close =  num(:,2);
    Volume =  num(:,6);
       
     timeNan = find(isnan(TimeStamp) == 1);
        CleanDate = 0;
     for y=1:size(timeNan,1);
         
         date = raw{timeNan(y),1};
         date = strrep(date, 'a','');
         date = str2num(date);
         
        CleanDate(timeNan(y),1) = date;
        currTime = date ;
        
        try
            for z = timeNan(y) + 1:timeNan(y+1) -1;
                adjTime = currTime + (num(z,1)*interval);
               CleanDate(z,1) = adjTime;
            end
        catch
             for z = timeNan(y) + 1: timeNan(y)+1000; %fix this later
                 try
                adjTime = currTime + (num(z,1)*interval);
               CleanDate(z,1) = adjTime;
                 catch
                 end
            end
        end
     end
     
    
    if (x ==1);
        FullDates = CleanDate;
        TableOpen(:,x) = Open(:,x);
        TableClose(:,x) = Close(:,x);
        TableHigh(:,x) = High(:,x);
        TableLow(:,x) = Low(:,x);
        TableVol(:,x) = Volume(:,x);
    else
        %create table of by matching FullDates with each CleanDate generated by file
        position = find(ismember(FullDates,CleanDate) == 1);
        
        for y = 1:size(position,1);
            TableOpen(position(y,1),x) = Open(y,1);
            TableClose(position(y,1),x) = Close(y,1);
            TableHigh(position(y,1),x) = High(y,1);
            TableLow(position(y,1),x) = Low(y,1);
            TableVol(position(y,1),x) = Volume(y,1);    
        end
        
    end
    disp(x);
end
     %this loop converts CleanDate (double) to a string, so it is readable
    DatesString = cell(0,0);
    for y = 1:size(FullDates,1)
        dateInStr = datetime( FullDates(y,1), 'ConvertFrom', 'posixtime' );
        DatesString{y,1} =  datestr( dateInStr);
    end

TableOpen(find(~TableOpen))   =NaN;
TableClose(find(~TableClose)) =NaN;
TableHigh(find(~TableHigh))   =NaN;
TableLow(find(~TableLow))     =NaN;
TableVol(find(~TableVol))     =NaN;

%###finish this later###
% nanCount = sum(isnan(TableOpen));
% f = find(nanCount < 200);
% TableOpen = TableOpen(:,f);
% TableClose = TableClose(:,f);
% TableHigh = TableHigh(:,f);
% TableLow = TableLow(:,f);
% TableVol = TableVol(:,f);
% list = list(f);
% 
% nanCount2 = sum(isnan(TableOpen),2);


for x = 1:size(list,2)
   list{1,x} = strrep(list{1,x},'.csv',''); 
end

% k = findstr(DateString{:}, '13:30');

xlswrite(filename,TableOpen,1,'C2')
xlswrite(filename,TableClose,2,'C2')
xlswrite(filename,TableHigh,3,'C2')
xlswrite(filename,TableLow,4,'C2')
xlswrite(filename,TableVol,5,'C2')


xlswrite(filename,DatesString,1,'B2')
xlswrite(filename,DatesString,2,'B2')
xlswrite(filename,DatesString,3,'B2')
xlswrite(filename,DatesString,4,'B2')
xlswrite(filename,DatesString,5,'B2')

xlswrite(filename,FullDates,1,'A2')
xlswrite(filename,FullDates,2,'A2')
xlswrite(filename,FullDates,3,'A2')
xlswrite(filename,FullDates,4,'A2')
xlswrite(filename,FullDates,5,'A2')

xlswrite(filename,list,1,'C1')
xlswrite(filename,list,2,'C1')
xlswrite(filename,list,3,'C1')
xlswrite(filename,list,4,'C1')
xlswrite(filename,list,5,'C1')
